# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Z3950-RadioMARC
version:      0.05
version_from: lib/Net/Z3950/RadioMARC.pm
installdirs:  site
requires:
    Net::Z3950:                    0.46

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
